### ISSUE TITLE
The library doesn't work anymore with PHP 8.1

### ISSUE THREAD

**Issue by jdecool** [thruway/client#15]
The PR #11 allow the `psr/log` v3 usage.
But this release has strict typing on `LoggerInterface` methods.

So it breaks the library compatibility because of inheritance incompatibility:

`Declaration of Thruway\Logging\ConsoleLogger::log($level, $message, array $context = []) must be compatible with Psr\Log\AbstractLogger::log($level, Stringable|string $message, array $context = []): void in /thruway/vendor/thruway/client/src/Logging/ConsoleLogger.php on line 22`

I suggest to revert this PR and start working on a new version for dedicated to PHP 8.

**Comment by ChargemapHakan** [comment]
I would like to back this. Our team at Chargemap could work on this PHP8 compatibility if that could help.

**Comment by mbonneau** [comment]
This is fixed in the latest release.
